# Generated by Django 4.0.4 on 2022-06-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, verbose_name='nick usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre usuario')),
                ('password', models.CharField(max_length=50, verbose_name='contraseña')),
                ('password2', models.CharField(max_length=50, verbose_name='confirmacion contraseña')),
                ('correo', models.EmailField(max_length=50, verbose_name='correo')),
            ],
        ),
    ]
